
motion:
  image: ikaritw/rpi-motion:latest
  container_name: motion
  devices:
    - /dev/video0:/dev/video0
  volumes:
    - ./motion.conf:/etc/motion/motion.conf
    - ./videos:/mnt/motion
  ports:
    - 8081:8081
    - 8080:8080

